<?php

declare(strict_types=1);

use BeastBytes\CodPhp\Writer\Markdown\Helpers;

echo sprintf(
    'Generated by %s',
    Helpers::a('CodPhp', 'https://github.com/BeastBytes/CodPhp', ['target' => '_blank'])
);
