<?php

declare(strict_types=1);

use BeastBytes\CodPhp\Element\ObjectElement;
use BeastBytes\CodPhp\Error\ErrorLevel;
use BeastBytes\CodPhp\Writer\Markdown\Helpers;
use BeastBytes\CodPhp\Writer\Writer;

/**
 * @var ?string $baseUrl
 * @var ObjectElement $element
 * @var string $namespace
 * @var ErrorLevel $errorLevel
 * @var Writer $this
 */

$output = '';

if ($element instanceof ObjectElement) {
    $output .= $this->render(
        '_object-footer',
        compact('element', 'namespace', 'errorLevel')
    );
}

$output .= sprintf(
    'Generated by %s',
    Helpers::a('CodPhp', 'https://github.com/beastbytes/cod-php', ['target' => '_blank'])
);

echo $output;